### ISSUE TITLE
Custom components

### ISSUE THREAD

**Issue by abhip10** [gorhom/react-native-paper-onboarding#11]
Is there a way to add custom components on the screen (for example, a button)?

**Comment by nghiatv** [comment]
Same question! Up Up Up

**Comment by gorhom** [comment]
Hi @abhip10, @nghiatv 

i'll work on it as soon as i get free time 👍

**Comment by abhip10** [comment]
thanks! Other than that, love the library!

**Comment by gorhom** [comment]
@abhip10 , @nghiatv  this feature been released with [v0.4.0](https://github.com/gorhom/react-native-paper-onboarding/releases/tag/v0.4.0) 🎉
