### ISSUE TITLE
use Image from React Native as image component

### ISSUE THREAD

**Issue by abhip10** [gorhom/react-native-paper-onboarding#12]
I attempted to use an image component as the image, but it didnt seem to work. Does it specifically need to be a react-native-svg?

**Comment by julien9999** [comment]
would be great, interested in that too

**Comment by julien9999** [comment]
@abhip10 actually it possible,
just pass in an Image component to icon or image.
`image: () => (
      <Image
        style={{
          height: 300,
          width: 300
        }}
        source={constants.Images.Illus2}
      />
    )`

**Comment by gorhom** [comment]
as @julien9999 mentioned , prop `image` and `icon` both accepts a react node, so it could be an image, svg or a view 👍
