### ISSUE TITLE
Content doesn't respond to touch

### ISSUE THREAD

**Issue by nastarfan** [gorhom/react-native-paper-onboarding#16]
When I use custom component for my page, touchables and other interactive components (such as Picker) inside the custom component doesn't respond to touch.

**Comment by gorhom** [comment]
hi @nastarfan , i will pick this up this weekend 👍

**Comment by gorhom** [comment]
this been solved with [v0.5.0](https://github.com/gorhom/react-native-paper-onboarding/releases/tag/v0.5.0) 🎉
