### ISSUE TITLE
Error while using with dependency react-native-svg

### ISSUE THREAD

**Issue by allandiego** [gorhom/react-native-paper-onboarding#31]
# Bug

using 
"@gorhom/paper-onboarding": "^1.1.0"
and
"react-native-svg": "12.1.0"

throws an error at app starts:
Tried to register two views with the same name RNSVGSvgView

removing react-native-svg fix the problem but i need to use both
## Environment info
Expo 41
"@gorhom/paper-onboarding": "^1.1.0",
"react-native-svg": "12.1.0",

**Comment by gorhom** [comment]
could you delete your node-modules and clear metro and try again ?

**Comment by allandiego** [comment]
same behavior, have you used both dependencies together?

**Comment by serdargun** [comment]
I resolved this problem with upgrading `react-native-svg`  from `12.1.0` to `12.1.1`

**Comment by allandiego** [comment]
"react-native-svg": "^12.1.1" solved
