### ISSUE TITLE
Great implementation, is there a JS alternative?

### ISSUE THREAD

**Issue by GodwinEbikwo** [gorhom/react-native-paper-onboarding#4]
Hi is this only capable if you are using .ts? I can't seem to get it work using javascript

**Comment by gorhom** [comment]
Hi @GodwinEbikwo ,

it should work fine with JavaScript project, but you could provide logs so i can help you :)

**Comment by GodwinEbikwo** [comment]
Ho @gorhom here is the issues encountered.
![image](https://user-images.githubusercontent.com/43885112/75754574-de6b4800-5d24-11ea-9aa3-f3a2cbd960a7.jpg)

**Comment by gorhom** [comment]
have you installed `react-native-reanimated`, `react-native-gesture-handler` & `react-native-svg` ?

https://github.com/gorhom/react-native-paper-onboarding#installation

**Comment by GodwinEbikwo** [comment]
Hi yes I did, all 3 packages were previously installed in my project

**Comment by gorhom** [comment]
@GodwinEbikwo could you share your dependencies version ? 
- react-native-reanimated
- react-native-gesture-handler
- react-native-svg
- react-native

**Comment by GodwinEbikwo** [comment]
Here is a list of my dependencies. Thanks for taking time to help me sort this out
Kind regards 
Godwin

**Comment by kukadiyaAni** [comment]
@gorhom I have installed all dependence still not work

here is my code
`const data = [
    {
        title: 'Hotels',
        description: 'All hotels and hostels are sorted by hospitality rating',
        color: '#698FB8',
    },
    {
        title: 'Banks',
        description: 'We carefully verify all banks before add them into the app',
        color: '#6CB2B8',

    },
    {
        title: 'Stores',
        description: 'All local stores are categorized for your convenience',
        color: '#9D8FBF',

    },
];

<View style={{ flex: 1 }}>
                <PaperOnboarding
                    data={data}
                    onCloseButtonPress={this.handleOnClosePress}
                />
            </View>
`

get output like below screenshot but slider not work

![Screenshot_1585994319](https://user-images.githubusercontent.com/16218216/78424154-139ee900-7689-11ea-910a-4e614710589f.png)

it's like gesture not working

**Comment by gorhom** [comment]
@kukadiyaAni have you followed the installation instruction for `react-native-gesture-handler` ?
https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html

**Comment by kukadiyaAni** [comment]
I have install `react-native-gesture-handler`  but not override createReactActivityDelegate

Now working fine after add createReactActivityDelegate method in MainActivity 

Thanks
